"""Export helpers: full Markdown package and focused CSV files.

All functions return strings (Markdown or CSV text) so the Streamlit UI can hand
them directly to download buttons. A convenience helper is also provided to save
a copy into the local ``outputs/`` folder.
"""

from __future__ import annotations

import csv
import io

from .sample_data import FIELD_LABELS
from .template_engine import SECTION_ORDER
from .utils import OUTPUTS_DIR, ensure_directories, now_iso, slugify, timestamp_slug


def to_markdown(package: dict) -> str:
    """Render a full knowledge-transfer package as a single Markdown document."""
    inputs = package["inputs"]
    title = inputs.get("process_name") or "Untitled Process"

    lines = [
        f"# Knowledge Transfer Package: {title}",
        "",
        f"_Generated by AI Knowledge Transfer & SOP Builder ({package['mode']}) on {now_iso()}._",
        "",
        "---",
        "",
    ]

    # Emit each section in the canonical order.
    for idx, title_key in enumerate(SECTION_ORDER, start=1):
        content = package["sections"].get(title_key, "_Not available._")
        lines.append(f"## {idx}. {title_key}")
        lines.append("")
        lines.append(content)
        lines.append("")

    # Append a compact record of the original inputs for traceability.
    lines.append("---")
    lines.append("")
    lines.append("## Appendix: Original Inputs")
    lines.append("")
    for key, label in FIELD_LABELS.items():
        value = (inputs.get(key) or "").strip() or "_Not provided._"
        lines.append(f"**{label}:**")
        lines.append("")
        lines.append(value)
        lines.append("")

    return "\n".join(lines)


def _rows_to_csv(fieldnames: list[str], rows: list[dict]) -> str:
    """Serialize a list of dictionaries to CSV text."""
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return buffer.getvalue()


def action_items_to_csv(package: dict) -> str:
    """Export the action-item tracker to CSV."""
    return _rows_to_csv(
        ["id", "action", "owner", "priority", "timeframe", "status"],
        package.get("action_items", []),
    )


def raci_to_csv(package: dict) -> str:
    """Export the RACI matrix to CSV."""
    return _rows_to_csv(
        ["task", "responsible", "accountable", "consulted", "informed"],
        package.get("raci", []),
    )


def risks_to_csv(package: dict) -> str:
    """Export the risks and gaps log to CSV."""
    return _rows_to_csv(
        ["id", "risk", "severity", "source", "mitigation", "owner", "status"],
        package.get("risks", []),
    )


def save_markdown_to_outputs(package: dict) -> str:
    """Write the Markdown package to the local ``outputs/`` folder.

    Returns the absolute path of the written file.
    """
    ensure_directories()
    name = slugify(package["inputs"].get("process_name"))
    filename = f"{name}_{timestamp_slug()}.md"
    path = OUTPUTS_DIR / filename
    path.write_text(to_markdown(package), encoding="utf-8")
    return str(path)
